server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.worldwire.model
---
spring:
  profiles: online
  datasource:
    name: worldwire
    url: jdbc:mysql://47.104.201.53:3306/worldwire
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: test
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver