server:
  port: 8090
spring:
  thymeleaf:
    mode: HTML5
  redis:
    database: 0
    host: 47.104.201.53
    port: 6379
    password:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
---
spring:
  profile: online
  datasource:
    name: worldwire
    url: jdbc:mysql://47.104.201.53:3306/worldwire?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.spring.worldwire.model
  
---
spring:
  profile: test
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.spring.worldwire.model